spring.application.name=joueurs2
spring.datasource.url=jdbc:mysql://localhost:3306/spring_DB_v2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/joueurs
server.port=8081
#spring.security.user.name=admin
#spring.security.user.password=123
# Keycloak OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/tayeb-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/tayeb-realm/protocol/openid-connect/certs