spring.application.name=oauth2
server.port=8087
spring.security.oauth2.client.registration.github.client-id=Ov23li8X6g2v1f1XaNJT
spring.security.oauth2.client.registration.github.client-secret=14b84c15040da2a0973aed9a1baf76568daa58e6